"""Layer 2 (Data) — emit lean-proof/TheoremaAureum/AutoLemmas.lean.

Reads data/hits.txt. Only the five Genesis lines drive lemma generation
(CI-trust rule). For each numeric Genesis line (e.g. 437, 1094), emits
`theorem hit_<n> : True := trivial`.

This module refuses to write any text containing `sorry`, `axiom `, or
`admit ` — a defence-in-depth guard so the lemma file cannot be turned
into an axiom-laundering surface even if the template is modified.

After writing AutoLemmas.lean, the bridge also ensures
`lean-proof/TheoremaAureum.lean` imports the new module so `lake build`
covers it. It then attempts to shell out to `lake env lean` to verify
that `#print axioms hit_437` reports no axioms; if `lake` is missing,
the script reports SKIPPED for the runtime check (the static guard
above still holds).

NOTE (honest-scope): every emitted lemma is the tautology `True`. The
*names* (hit_437, hit_1094) reference the OpenCV cube counts from
README Appendix A; the *statements* claim nothing about number theory.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
HITS = REPO_ROOT / "data" / "hits.txt"
LEAN_DIR = REPO_ROOT / "lean-proof"
OUT = LEAN_DIR / "TheoremaAureum" / "AutoLemmas.lean"
ROOT_LEAN = LEAN_DIR / "TheoremaAureum.lean"
IMPORT_LINE = "import TheoremaAureum.AutoLemmas"

SEAL_MARKER = "--- GENESIS SEAL ---"

HEADER = """\
-- AUTOGENERATED by lean_bridge.py. Do not edit by hand.
-- Every theorem here is `True := trivial`. Axiom debt is [].
-- Names reference OpenCV cube counts from README Appendix A and claim
-- nothing about number theory. See data/M13_CERT.txt for scope notes.

namespace TheoremaAureum
namespace AutoLemmas

"""

FOOTER = """\

end AutoLemmas
end TheoremaAureum
"""

FORBIDDEN = ("sorry", "axiom ", "admit ")


def _genesis_integers() -> list[int]:
    """Read non-comment Genesis lines (up to the SEAL_MARKER) and return ints.

    Header comments (`# ...`) are skipped. The Genesis is everything
    between the comment header and the SEAL_MARKER, inclusive of the 5
    enumerated frozen lines. Only purely numeric Genesis lines drive
    lemma generation — this is the CI-trust rule from the task spec.
    """
    if not HITS.exists():
        raise SystemExit(f"FATAL: {HITS} missing.")
    lines = HITS.read_text(encoding="utf-8").splitlines()
    try:
        marker_idx = lines.index(SEAL_MARKER)
    except ValueError as e:
        raise SystemExit(
            f"FATAL: data/hits.txt missing required marker {SEAL_MARKER!r}."
        ) from e
    nums: list[int] = []
    for raw in lines[:marker_idx]:
        s = raw.strip()
        if not s or s.startswith("#"):
            continue
        if s.isdigit():
            nums.append(int(s))
    if not nums:
        raise SystemExit("FATAL: no numeric Genesis lines found in hits.txt.")
    return nums


def _render(nums: list[int]) -> str:
    parts = [HEADER]
    for n in nums:
        parts.append(f"theorem hit_{n} : True := trivial\n")
    parts.append(FOOTER)
    return "".join(parts)


def _guard(text: str) -> None:
    """Reject `sorry`/`axiom `/`admit ` outside Lean line comments.

    Lean line comments start with `--`. We strip them before scanning so
    that documentation in the header (e.g. 'Axiom debt is []') doesn't
    trip the guard. Block comments are not used in the generated file.
    """
    for raw in text.splitlines():
        code = raw.split("--", 1)[0]
        lowered = code.lower()
        for bad in FORBIDDEN:
            if bad in lowered:
                raise SystemExit(
                    f"FATAL: refused to emit Lean containing {bad!r} (line: {raw!r})."
                )


def _ensure_import() -> None:
    """Ensure TheoremaAureum.lean imports AutoLemmas (idempotent)."""
    if not ROOT_LEAN.exists():
        raise SystemExit(f"FATAL: {ROOT_LEAN} missing.")
    text = ROOT_LEAN.read_text(encoding="utf-8")
    if IMPORT_LINE in text:
        return
    new_text = text.rstrip() + "\n" + IMPORT_LINE + "\n"
    ROOT_LEAN.write_text(new_text, encoding="utf-8")


def _runtime_axiom_check(nums: list[int]) -> str:
    """Runtime check via `lake env lean`. Returns 'ok' or raises.

    The task contract requires the bridge to fail loudly if the axiom
    check cannot be confirmed; there is no SKIPPED success path.
    """
    if shutil.which("lake") is None:
        raise SystemExit(
            "FATAL: `lake` not on PATH; the axiom check cannot be confirmed. "
            "Install Lean 4 / elan and re-run."
        )
    # Build first so the AutoLemmas .olean exists for the import below.
    build = subprocess.run(
        ["lake", "build"],
        cwd=str(LEAN_DIR),
        capture_output=True,
        text=True,
        timeout=600,
    )
    if build.returncode != 0:
        raise SystemExit(
            f"FATAL: lake build failed:\n{(build.stdout or '') + (build.stderr or '')}"
        )
    targets = [f"TheoremaAureum.AutoLemmas.hit_{n}" for n in nums]
    snippet = "\n".join(f"#print axioms {t}" for t in targets) + "\n"
    probe = LEAN_DIR / "_AutoLemmas_Verify.lean"
    probe.write_text("import TheoremaAureum.AutoLemmas\n" + snippet, encoding="utf-8")
    try:
        res = subprocess.run(
            ["lake", "env", "lean", probe.name],
            cwd=str(LEAN_DIR),
            capture_output=True,
            text=True,
            timeout=300,
        )
    finally:
        try:
            probe.unlink()
        except OSError:
            pass
    out = (res.stdout or "") + (res.stderr or "")
    if res.returncode != 0:
        raise SystemExit(f"FATAL: lake env lean failed:\n{out}")
    for t in targets:
        needle = f"'{t}' does not depend on any axioms"
        if needle not in out:
            raise SystemExit(
                f"FATAL: axiom check did not confirm `{t}` is axiom-free.\n"
                f"--- output ---\n{out}"
            )
    return "ok"


def main() -> int:
    nums = _genesis_integers()
    rendered = _render(nums)
    _guard(rendered)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    _ensure_import()
    status = _runtime_axiom_check(nums)
    print(f"wrote {OUT}")
    print(f"ensured import in {ROOT_LEAN}: {IMPORT_LINE}")
    print(f"axiom check: {status}")
    print(f"genesis-derived lemmas: {', '.join('hit_' + str(n) for n in nums)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
