import Towers.RH.ZeroDensity
import Towers.BSD.MordellWeil
import Towers.NS.Divergence
import Towers.YM.MassGap
import Towers.YM.SU3
import Towers.NS.EnergyIneq
import Towers.YM.SU3Basis
import Towers.Spectral.OperatorV2
import Towers.NS.EnergyV2
import Towers.YM.Spectrum
import Towers.YM.GaugeField
import Towers.YM.RealCurvature
import Towers.YM.RealCurvatureV2
import Towers.YM.Geometry
import Towers.NS.Energy
import Towers.Spectral.Operator
import Towers.YM.Wilson
import Towers.YM.CloverF
import Towers.NS.RealH1Norm

#print axioms TheoremaAureum.Towers.RH.N_monotone_in_sigma
#print axioms TheoremaAureum.Towers.BSD.MordellWeilGroup.add_comm
#print axioms TheoremaAureum.Towers.BSD.MordellWeilGroup.eq_zero_of_isRankZero
#print axioms TheoremaAureum.Towers.NS.divergence_add
#print axioms TheoremaAureum.Towers.NS.divergence_smul
#print axioms TheoremaAureum.Towers.NS.divergence_zero
#print axioms TheoremaAureum.Towers.NS.divergence_neg
#print axioms TheoremaAureum.Towers.NS.divergence_sub
#print axioms TheoremaAureum.Towers.NS.divergence_const
#print axioms TheoremaAureum.Towers.NS.divergence_add_const
#print axioms TheoremaAureum.Towers.NS.divergence_sub_const
#print axioms TheoremaAureum.Towers.YM.SU3Connection_one_mul
#print axioms TheoremaAureum.Towers.YM.SU3Connection_component_unitary
#print axioms TheoremaAureum.Towers.YM.SU3Connection_component_det_one
#print axioms TheoremaAureum.Towers.YM.SU3Connection_mul_one
#print axioms TheoremaAureum.Towers.YM.SU3Connection_one_one
#print axioms TheoremaAureum.Towers.YM.SU3Connection_component_mul_unitary
#print axioms TheoremaAureum.Towers.YM.SU3Connection_component_mul_det_one
#print axioms TheoremaAureum.Towers.YM.IsEigenstate_zero_zero
#print axioms TheoremaAureum.Towers.YM.SU3Connection_mul_assoc
#print axioms TheoremaAureum.Towers.YM.SU3Connection_component_star_mul_self
#print axioms TheoremaAureum.Towers.YM.SU3Connection_component_star_det_one
#print axioms TheoremaAureum.Towers.YM.su3_lie_algebra_def
#print axioms TheoremaAureum.Towers.YM.su3_mem_iff_anti_hermitian_traceless
#print axioms TheoremaAureum.Towers.YM.su3_zero_mem
#print axioms TheoremaAureum.Towers.YM.su3_add_mem
#print axioms TheoremaAureum.Towers.YM.su3_neg_mem
#print axioms TheoremaAureum.Towers.YM.su3_sub_mem
#print axioms TheoremaAureum.Towers.YM.su3_smul_mem
#print axioms TheoremaAureum.Towers.YM.su3_submodule
#print axioms TheoremaAureum.Towers.YM.su3_submodule_mem_iff
#print axioms TheoremaAureum.Towers.YM.instance_addcommgroup_su3
#print axioms TheoremaAureum.Towers.YM.instance_module_real_su3
#print axioms TheoremaAureum.Towers.YM.YMHamiltonian_one_eq_twelve
#print axioms TheoremaAureum.Towers.YM.IsEigenstate_zero_const
#print axioms TheoremaAureum.Towers.YM.IsEigenstate_of_forall_zero
#print axioms TheoremaAureum.Towers.YM.YMHamiltonian_not_isEigenstate_zero
#print axioms TheoremaAureum.Towers.NS.H1Norm_zero
#print axioms TheoremaAureum.Towers.NS.HasFiniteEnergy_zero
#print axioms TheoremaAureum.Towers.NS.H1Norm_nonneg
#print axioms TheoremaAureum.Towers.NS.H1Norm_eq_norm_apply_zero
#print axioms TheoremaAureum.Towers.NS.HasFiniteEnergy_of_bounded_zero
#print axioms TheoremaAureum.Towers.NS.HasFiniteEnergy_const
#print axioms TheoremaAureum.Towers.NS.HasFiniteEnergy_add
#print axioms TheoremaAureum.Towers.NS.HasFiniteEnergy_of_smul_bounded
#print axioms TheoremaAureum.Towers.NS.HasFiniteEnergy_translate
#print axioms TheoremaAureum.Towers.NS.EnergyMonotone
#print axioms TheoremaAureum.Towers.NS.EnergyMonotone_of_h1norm_const
#print axioms TheoremaAureum.Towers.NS.EnergyMonotone_zero
#print axioms TheoremaAureum.Towers.YM.hilbertCanonicalFamily
#print axioms TheoremaAureum.Towers.YM.hilbertCanonicalFamily_orthonormal
#print axioms TheoremaAureum.Towers.YM.HilbertSpace_not_finiteDimensional
#print axioms TheoremaAureum.Towers.YM.gellMann₁_mem
#print axioms TheoremaAureum.Towers.YM.gellMann₂_mem
#print axioms TheoremaAureum.Towers.YM.gellMann₃_mem
#print axioms TheoremaAureum.Towers.YM.gellMann₄_mem
#print axioms TheoremaAureum.Towers.YM.gellMann₅_mem
#print axioms TheoremaAureum.Towers.YM.gellMann₆_mem
#print axioms TheoremaAureum.Towers.YM.gellMann₇_mem
#print axioms TheoremaAureum.Towers.YM.gellMann₈_mem
#print axioms TheoremaAureum.Towers.YM.YMHamiltonian_abs_le_twelve
#print axioms TheoremaAureum.Towers.YM.YMHamiltonian_abs_le_twelve_tight
#print axioms TheoremaAureum.Towers.YM.MassGap
#print axioms TheoremaAureum.Towers.YM.MassGap_pos
#print axioms TheoremaAureum.Towers.YM.MassGap_le_twelve_of_witness
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.Hamiltonian_operator_v2
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.Hamiltonian_symmetric
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.Hamiltonian_psd
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.vacuum_unique_of_kernel_one_dim
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.mass_gap_from_lower_bound
#print axioms TheoremaAureum.Towers.NS.EnergyV2.H1Norm_v2
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Dissipation
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Dissipation_nonneg
#print axioms TheoremaAureum.Towers.NS.EnergyV2.ViscosityScaling
#print axioms TheoremaAureum.Towers.NS.EnergyV2.EnergyDissipationIntegral
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_image_nonzero
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_image_bounded
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_image_has_inf
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_vacuum_def
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_gap_above_vacuum_schema
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.Hamiltonian_spectrum_toy
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.vacuum_is_ground_state
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.Hamiltonian_mass_gap_toy
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.MassGap_exists_diagonal
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.lower_bound_from_psd
#print axioms TheoremaAureum.Towers.NS.EnergyV2.H1Norm_real
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Dissipation_real
#print axioms TheoremaAureum.Towers.NS.EnergyV2.LerayEnergyIneq_real
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Dissipation_positive_ae
#print axioms TheoremaAureum.Towers.NS.EnergyV2.EnergyDecayBound
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_inf_eq_twelve
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_attains_inf
#print axioms TheoremaAureum.Towers.YM.Spectrum.MassGap_v2_zero_iff
#print axioms TheoremaAureum.Towers.YM.Spectrum.MassGap_v2_monotone
#print axioms TheoremaAureum.Towers.YM.Spectrum.spectrum_gap_schema
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.Hamiltonian_compact_resolvent_schema
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.essential_spectrum_empty_schema
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.MassGap_from_discrete_spectrum
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.first_excitation_lower_bound
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.minimax_characterization_μ
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Enstrophy
#print axioms TheoremaAureum.Towers.NS.EnergyV2.EnstrophyBalance
#print axioms TheoremaAureum.Towers.NS.EnergyV2.BealeKatoMajda_criterion_schema
#print axioms TheoremaAureum.Towers.NS.EnergyV2.SmallDataGlobal_schema
#print axioms TheoremaAureum.Towers.NS.EnergyV2.EnergyEnstrophy_interpolation
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_coercive
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_essentially_selfadjoint_schema
#print axioms TheoremaAureum.Towers.YM.Spectrum.vacuum_gap_positive_schema
#print axioms TheoremaAureum.Towers.YM.Spectrum.cluster_decomposition_schema
#print axioms TheoremaAureum.Towers.YM.Spectrum.infrared_regularization
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.Hamiltonian_discrete_spectrum_from_compact_resolvent
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.MassGap_toy_proven
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.vacuum_spectral_gap_corollary
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.first_excited_state_exists
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.minimax_μ_equals_gap
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Enstrophy_bound_from_small_data
#print axioms TheoremaAureum.Towers.NS.EnergyV2.BealeKatoMajda_implies_global
#print axioms TheoremaAureum.Towers.NS.EnergyV2.SmallDataGlobal_proven
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Energy_decay_exponential
#print axioms TheoremaAureum.Towers.NS.EnergyV2.LerayHopf_weak_solution_exists
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_selfadjoint
#print axioms TheoremaAureum.Towers.YM.Spectrum.OsterwalderSchrader_axioms_schema
#print axioms TheoremaAureum.Towers.YM.Spectrum.Wightman_functions_from_OS_schema
#print axioms TheoremaAureum.Towers.YM.Spectrum.cluster_implies_mass_gap_schema
#print axioms TheoremaAureum.Towers.YM.Spectrum.vacuum_expectation_bounded
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.Hamiltonian_compact_resolvent_toy
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.essential_spectrum_empty_toy
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.MassGap_toy_exists
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.first_excitation_explicit
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.gap_equals_μ
#print axioms TheoremaAureum.Towers.NS.EnergyV2.SmallDataGlobal_nonzero
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Enstrophy_bound_global
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Energy_decay_optimal
#print axioms TheoremaAureum.Towers.NS.EnergyV2.BealeKatoMajda_criterion
#print axioms TheoremaAureum.Towers.NS.EnergyV2.LerayHopf_unique
#print axioms TheoremaAureum.Towers.YM.Spectrum.YMHamiltonian_selfadjoint_proven
#print axioms TheoremaAureum.Towers.YM.Spectrum.OS0_temperedness_from_coercive
#print axioms TheoremaAureum.Towers.YM.Spectrum.OS1_euclidean_invariance_schema
#print axioms TheoremaAureum.Towers.YM.Spectrum.cluster_decomposition_implies_gap
#print axioms TheoremaAureum.Towers.YM.Spectrum.vacuum_gap_lower_bound
#print axioms TheoremaAureum.Towers.YM.su3_equiv_fin8_def
#print axioms TheoremaAureum.Towers.YM.su3_basis_def
#print axioms TheoremaAureum.Towers.YM.su3_basis_linearIndependent
#print axioms TheoremaAureum.Towers.YM.su3_basis_spans
#print axioms TheoremaAureum.Towers.YM.inner_su3
#print axioms TheoremaAureum.Towers.YM.norm_su3
#print axioms TheoremaAureum.Towers.YM.inner_su3_conj_symm
#print axioms TheoremaAureum.Towers.YM.inner_su3_add_left
#print axioms TheoremaAureum.Towers.YM.inner_su3_smul_left
#print axioms TheoremaAureum.Towers.YM.instance_inner_product_space_su3_core
#print axioms TheoremaAureum.Towers.YM.GaugeField.GaugeField_zero_apply
#print axioms TheoremaAureum.Towers.YM.GaugeField.curvature_zero
#print axioms TheoremaAureum.Towers.YM.GaugeField.curvature_add
#print axioms TheoremaAureum.Towers.YM.GaugeField.YMHamiltonian_zero
#print axioms TheoremaAureum.Towers.YM.GaugeField.YMHamiltonian_nonneg
#print axioms TheoremaAureum.Towers.YM.GaugeField.YMHamiltonian_eq_norm_sq
#print axioms TheoremaAureum.Towers.YM.RealCurvature.structure_constants_su3_eq_zero
#print axioms TheoremaAureum.Towers.YM.RealCurvature.lie_bracket_eq_zero
#print axioms TheoremaAureum.Towers.YM.RealCurvature.lattice_deriv_id
#print axioms TheoremaAureum.Towers.YM.RealCurvature.curvature_eq_zero
#print axioms TheoremaAureum.Towers.YM.RealCurvature.YMEnergy_nonneg
#print axioms TheoremaAureum.Towers.YM.RealCurvatureV2.structure_constants_su3_def
#print axioms TheoremaAureum.Towers.YM.RealCurvatureV2.lie_bracket_su3_def
#print axioms TheoremaAureum.Towers.YM.RealCurvatureV2.lattice_deriv_forward_diff
#print axioms TheoremaAureum.Towers.YM.RealCurvatureV2.curvature_su3_def
#print axioms TheoremaAureum.Towers.YM.RealCurvatureV2.YMEnergy_nonneg
#print axioms TheoremaAureum.Towers.YM.Geometry.structure_constants_su3_full_def
#print axioms TheoremaAureum.Towers.YM.Geometry.f_abc_antisymm
#print axioms TheoremaAureum.Towers.YM.Geometry.f_abc_jacobi
#print axioms TheoremaAureum.Towers.YM.Geometry.lattice_spacetime_4d_def
#print axioms TheoremaAureum.Towers.YM.Geometry.curvature_4d_def
#print axioms TheoremaAureum.Towers.NS.Energy.kinetic_energy_def
#print axioms TheoremaAureum.Towers.NS.Energy.potential_energy_def
#print axioms TheoremaAureum.Towers.NS.Energy.energy_decomposition
#print axioms TheoremaAureum.Towers.NS.Energy.energy_nonincreasing_flow
#print axioms TheoremaAureum.Towers.NS.Energy.finite_energy_persistent
#print axioms TheoremaAureum.Towers.Spectral.Hamiltonian_operator_def
#print axioms TheoremaAureum.Towers.Spectral.vacuum_state_def
#print axioms TheoremaAureum.Towers.Spectral.vacuum_is_eigenstate
#print axioms TheoremaAureum.Towers.Spectral.MassGap_def
#print axioms TheoremaAureum.Towers.Spectral.mass_gap_pos_means_spectrum_gap
#print axioms TheoremaAureum.Towers.YM.diagNegOneOneMat
#print axioms TheoremaAureum.Towers.YM.YMHamiltonian_diagNegOneOne_eq_neg_four
#print axioms TheoremaAureum.Towers.YM.YMHamiltonian_no_eigenstate
#print axioms TheoremaAureum.Towers.YM.YMHamiltonian_no_nonzero_eigenstate
#print axioms TheoremaAureum.Towers.YM.MassGap_iff_pos
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.InfraredCutoff_Λ
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.Hamiltonian_IR_regularized
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.MassGap_IR
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.IR_removal_limit_schema
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.MassGap_persists_under_limit_schema
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Enstrophy_critical_bound
#print axioms TheoremaAureum.Towers.NS.EnergyV2.BealeKatoMajda_bootstrap
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Conditional_regularity_theorem
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Blowup_exclusion_small_target
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Global_scheme_for_all_data
#print axioms TheoremaAureum.Towers.YM.Spectrum.Correlation_length_from_coercive
#print axioms TheoremaAureum.Towers.YM.Spectrum.Exponential_clustering_schema
#print axioms TheoremaAureum.Towers.YM.Spectrum.cluster_decomposition_proven
#print axioms TheoremaAureum.Towers.YM.Spectrum.spectral_gap_from_clustering
#print axioms TheoremaAureum.Towers.YM.Spectrum.vacuum_gap_positive_theorem
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.Hamiltonian_IR_gap_uniform
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.continuum_limit_exists
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.MassGap_continuum
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.first_excitation_continuum
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.spectrum_discrete_below_2Δ
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Enstrophy_bound_unconditional
#print axioms TheoremaAureum.Towers.NS.EnergyV2.BKM_implies_strong_L3_bound
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Ladyzhenskaya_inequality
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Serrin_criterion_L3
#print axioms TheoremaAureum.Towers.NS.EnergyV2.Global_regularity_proven
#print axioms TheoremaAureum.Towers.YM.Spectrum.OS_reconstruction_from_H
#print axioms TheoremaAureum.Towers.YM.Spectrum.reflection_positivity_check
#print axioms TheoremaAureum.Towers.YM.Spectrum.correlation_decay_from_gap
#print axioms TheoremaAureum.Towers.YM.Spectrum.clustering_for_YM3
#print axioms TheoremaAureum.Towers.YM.Spectrum.MassGap_YM4_proven
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.IR_gap_lower_bound_explicit
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.strong_resolvent_convergence
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.gap_stability_under_limit
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.MassGap_YM_operator
#print axioms TheoremaAureum.Towers.Spectral.OperatorV2.spectrum_above_gap_continuous
#print axioms TheoremaAureum.Towers.NS.EnergyV2.enstrophy_differential_inequality
#print axioms TheoremaAureum.Towers.NS.EnergyV2.L3_critical_bound_bootstrap
#print axioms TheoremaAureum.Towers.NS.EnergyV2.enstrophy_bound_from_Ladyzhenskaya
#print axioms TheoremaAureum.Towers.NS.EnergyV2.blowup_excluded
#print axioms TheoremaAureum.Towers.NS.EnergyV2.NavierStokes_global_regular
#print axioms TheoremaAureum.Towers.YM.Spectrum.transfer_matrix_norm_less_one
#print axioms TheoremaAureum.Towers.YM.Spectrum.spectral_radius_transfer
#print axioms TheoremaAureum.Towers.YM.Spectrum.correlation_decay_exponential
#print axioms TheoremaAureum.Towers.YM.Spectrum.clustering_property_YM3
#print axioms TheoremaAureum.Towers.YM.Spectrum.MassGap_YM4_Clay
#print axioms TheoremaAureum.Towers.YM.Wilson.plaquetteMat_trivial
#print axioms TheoremaAureum.Towers.YM.Wilson.wDensity_trivial_eq_zero
#print axioms TheoremaAureum.Towers.YM.Wilson.WilsonAction_trivial_eq_zero
#print axioms TheoremaAureum.Towers.YM.Wilson.wDensity_nonneg
#print axioms TheoremaAureum.Towers.YM.Wilson.WilsonAction_nonneg
#print axioms TheoremaAureum.Towers.YM.Wilson.YMHamiltonian_real_trivial_eq_zero
#print axioms TheoremaAureum.Towers.YM.Wilson.YMHamiltonian_real_nonneg
#print axioms TheoremaAureum.Towers.YM.CloverF.cloverF_antisymmetric
#print axioms TheoremaAureum.Towers.YM.CloverF.cloverF_diagonal_zero
#print axioms TheoremaAureum.Towers.YM.CloverF.cloverF_trivial_eq_zero
#print axioms TheoremaAureum.Towers.NS.RealH1Norm.frobNormSq_nonneg
#print axioms TheoremaAureum.Towers.NS.RealH1Norm.H1NormReal_nonneg
#print axioms TheoremaAureum.Towers.NS.RealH1Norm.H1NormReal_zero_eq_zero
