-- AUTOGENERATED by morningstar-lab/lean_bridge.py.
-- Every theorem here is `True := trivial`. Axiom debt is [].
-- This file is NOT part of the TheoremaAureum certified spine.

namespace MorningStarLab

theorem hit_437 : True := trivial
theorem hit_1094 : True := trivial

end MorningStarLab

#print axioms MorningStarLab.hit_437
#print axioms MorningStarLab.hit_1094
