"""Layer 2 (Data) — lean_bridge.py.

Reads data/hits.txt and emits lean/AutoLemmas.lean containing one
trivial theorem per integer line in the seed.

Honest-scope: every emitted lemma has body `:= trivial` and statement
`True`. The *name* (hit_437, hit_1094) references the OpenCV cube counts
from README Appendix A; the *statement* is the tautology True and
therefore has axiom debt []. Nothing here claims 437 or 1094 has any
number-theoretic content. This is the entire point: the bridge must be
unable to launder an unproved claim into Lean.

This module never emits `sorry` and never emits `axiom`. The integer
extraction below also rejects any name that could collide with a real
TheoremaAureum identifier.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
HITS = HERE / "data" / "hits.txt"
OUT = HERE / "lean" / "AutoLemmas.lean"

HEADER = """\
-- AUTOGENERATED by morningstar-lab/lean_bridge.py.
-- Every theorem here is `True := trivial`. Axiom debt is [].
-- This file is NOT part of the TheoremaAureum certified spine.

namespace MorningStarLab

"""

FOOTER = """
end MorningStarLab

#print axioms MorningStarLab.hit_437
#print axioms MorningStarLab.hit_1094
"""


def _integer_lines(text: str) -> list[int]:
    out: list[int] = []
    for raw in text.splitlines():
        s = raw.strip()
        if s.isdigit():
            out.append(int(s))
    return out


def emit() -> Path:
    if not HITS.exists():
        raise SystemExit(f"FATAL: {HITS} missing; run lab.py --seed first.")
    body = HITS.read_text(encoding="utf-8")
    nums = _integer_lines(body)
    if not nums:
        raise SystemExit("FATAL: no integer seed lines in hits.txt.")
    lines = [HEADER]
    for n in nums:
        # Defence in depth: refuse to emit anything but `True := trivial`.
        lines.append(f"theorem hit_{n} : True := trivial\n")
    lines.append(FOOTER)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    rendered = "".join(lines)
    if "sorry" in rendered or "axiom " in rendered:
        raise SystemExit("FATAL: refused to emit Lean containing sorry/axiom.")
    OUT.write_text(rendered, encoding="utf-8")
    return OUT


if __name__ == "__main__":
    path = emit()
    print(f"wrote {path}")
    sys.exit(0)
